<template>
  <Welcome :data="testContent.welcome" />
  <ImageArticle
    :data="testContent.imageArticle"
    component="list"
    button-style="outline"
    image-to-right
    textAlignment="left"
    button-alignment="left"
    title-size="large"
    direction="columnReverse"
  />
  <IconBoxes
    :data="testContent.iconBoxesWithTitles"
    title-position="center"
    icon-to-top
  />
  <ContactForm
    type="simplified"
    component="list"
    formToLeft
    :data="testContent.contactFormSimplified"
  />
  <IconBoxes
    :data="testContent.iconBoxesWithoutTitles"
    title-position="center"
  />
  <ContactForm
    type="extended"
    :data="testContent.contactFormExtended"
  />
  <ImageBoxes
    :data="testContent.imageBoxesWithTestimonial"
  />
  <ImageBoxes
    :data="testContent.imageBoxesWithoutTestimonial"
  />
  <ImageBoxes
    title-position="left"
    :data="testContent.imageBoxesWithoutDescription"
  />
  <SquaresTimeline
    title-position="left"
    :data="testContent.squaresTimeline"
  />
  <TextBoxes
    title-position="left"
    :data="testContent.textBoxes"
  />
  <TextBoxes
    text-alignment="center"
    :data="testContent.textBoxesWithoutIcons"
  />
  <TabbedContent
    titlePosition="left"
    :data="testContent.tabsIcons"
    component="IconBox"
    icons-background="transparent"
  />
  <TabbedContent
    titlePosition="left"
    :data="testContent.tabsIconsWithText"
    component="IconBox"
    icons-background="transparent"
  />
  <TabbedContent
    titlePosition="left"
    :data="testContent.tabsImageBox"
    component="ImageBox"
  />
  <TabbedContent
    titlePosition="left"
    :data="testContent.tabsImageBoxWithoutTestimonial"
    component="ImageBox"
  />
  <TabbedContent
    titlePosition="left"
    :data="testContent.tabsImageBoxWithoutDescripton"
    component="ImageBox"
  />
  <LeadForm
    :data="testContent.leadForm"
    browserBackEvent
    pageScrollEvent
    timer-event
    :percent-to-scroll="50"
    :sec-to-trigger="10"
  />
</template>
  

<script setup lang="ts">
import testContent from '../content/test.json';

const store = useContentStore();
store.setPageContent(testContent);
</script>